"""
PDF Report Generation for Social Media Analytics
=================================================

Builds a simple PDF with report title, date range, KPIs, and top posts.
Uses reportlab when available; otherwise returns None (no PDF button).
"""

import io
from datetime import datetime
from typing import Any, Dict, List, Optional

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False


def _get_report_title() -> str:
    try:
        from app.config.settings import REPORT_TITLE

        return REPORT_TITLE or "Social Media Analytics Report"
    except Exception:
        return "Social Media Analytics Report"


def _get_report_footer() -> str:
    try:
        from app.config.settings import REPORT_FOOTER

        return REPORT_FOOTER or "Generated by Social Media Analytics"
    except Exception:
        return "Generated by Social Media Analytics"


def _kpi_row(posts: List[Dict], platform: str) -> List[tuple]:
    """Compute KPI row for PDF table. Returns list of (metric_name, value) for current platform."""
    try:
        from app.analytics import get_post_reactions_count, get_post_engagement
    except Exception:
        return []

    if not posts:
        return []

    total_reactions = sum(get_post_reactions_count(p) for p in posts)
    total_comments = sum(p.get("comments_count", 0) or 0 for p in posts)
    total_shares = sum(p.get("shares_count", 0) or 0 for p in posts)
    try:
        engagement_sum = sum(
            (get_post_engagement(p, platform) or 0) if p else 0 for p in posts
        )
        avg_engagement = engagement_sum / len(posts) if posts else 0
    except (TypeError, ZeroDivisionError):
        avg_engagement = 0

    if platform == "Facebook":
        return [
            ("Total Reactions", f"{total_reactions:,}"),
            ("Total Comments", f"{total_comments:,}"),
            ("Total Shares", f"{total_shares:,}"),
            ("Avg Engagement", f"{avg_engagement:.1f}"),
        ]
    if platform == "YouTube":
        total_views = sum(p.get("views", 0) or 0 for p in posts)
        return [
            ("Total Views", f"{total_views:,}"),
            ("Total Likes", f"{sum(p.get('likes', 0) for p in posts):,}"),
            ("Total Comments", f"{total_comments:,}"),
            ("Posts", str(len(posts))),
        ]
    # Instagram / generic
    total_likes = sum(p.get("likes", 0) or 0 for p in posts)
    return [
        ("Total Likes", f"{total_likes:,}"),
        ("Total Comments", f"{total_comments:,}"),
        ("Posts", str(len(posts))),
        ("Avg Engagement", f"{avg_engagement:.1f}"),
    ]


def build_pdf_report(
    posts: List[Dict],
    platform: str,
    date_range_str: Optional[str] = None,
) -> Optional[bytes]:
    """
    Build PDF report bytes. Returns None if reportlab is not installed.

    Args:
        posts: List of normalized posts
        platform: Platform name (Facebook, Instagram, YouTube)
        date_range_str: Optional "YYYY-MM-DD to YYYY-MM-DD"

    Returns:
        PDF file bytes or None
    """
    if not REPORTLAB_AVAILABLE or not posts:
        return None

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        name="ReportTitle",
        parent=styles["Heading1"],
        fontSize=16,
        spaceAfter=12,
    )
    h2_style = styles["Heading2"]
    normal = styles["Normal"]

    story = []

    title = _get_report_title()
    story.append(Paragraph(title, title_style))
    story.append(Paragraph(f"<b>Platform:</b> {platform}", normal))
    story.append(
        Paragraph(f"<b>Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M')}", normal)
    )
    if date_range_str:
        story.append(Paragraph(f"<b>Data range:</b> {date_range_str}", normal))
    story.append(Spacer(1, 0.3 * inch))

    # KPI table
    story.append(Paragraph("Key metrics", h2_style))
    kpi_data = _kpi_row(posts, platform)
    if kpi_data:
        table_data = [["Metric", "Value"]] + list(kpi_data)
        t = Table(table_data, colWidths=[3 * inch, 2 * inch])
        t.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
                    ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ]
            )
        )
        story.append(t)
    story.append(Spacer(1, 0.3 * inch))

    # Top 5 posts (guard against missing/non-numeric engagement)
    try:
        from app.analytics import get_post_engagement
    except Exception:
        get_post_engagement = lambda p, _: (
            (p.get("likes") or 0) + (p.get("comments_count") or 0) + (p.get("shares_count") or 0)
        )
    posts_with_eng = []
    for p in posts:
        try:
            eng = get_post_engagement(p, platform)
            eng = int(eng) if eng is not None and isinstance(eng, (int, float)) else 0
        except (TypeError, ValueError):
            eng = 0
        posts_with_eng.append((p, eng))
    posts_with_eng.sort(key=lambda x: x[1], reverse=True)
    top5 = posts_with_eng[:5]

    story.append(Paragraph("Top 5 posts by engagement", h2_style))
    rows = [["Caption (excerpt)", "Engagement"]]
    for p, eng in top5:
        text = (p.get("text") or "")[:80].replace("\n", " ") + (
            "..." if len(p.get("text") or "") > 80 else ""
        )
        rows.append([text, str(int(eng))])
    if len(rows) > 1:
        t2 = Table(rows, colWidths=[4 * inch, 1.2 * inch])
        t2.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                    ("ALIGN", (0, 0), (0, -1), "LEFT"),
                    ("ALIGN", (1, 0), (1, -1), "RIGHT"),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ]
            )
        )
        story.append(t2)

    story.append(Spacer(1, 0.5 * inch))
    story.append(
        Paragraph(
            _get_report_footer(),
            ParagraphStyle(name="Footer", parent=normal, fontSize=8, textColor=colors.grey),
        )
    )

    doc.build(story)
    buf.seek(0)
    return buf.read()
